import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";

// import "primereact/resources/primereact.css";
// import "/node_modules/primeflex/primeflex.css";

import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import StoreProvider from "@/store/StoreProvider";
import ToastProvider from "@/component/general/ToastProvider";
import { SocketProvider } from "@/context/SocketProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider>
          <StoreProvider>
            <ToastProvider>
              <SocketProvider>
                {children}
              </SocketProvider>
            </ToastProvider>
          </StoreProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
